### ISSUE TITLE
Two default exports in profile page

### ISSUE THREAD

**Issue by w01fgang** [Thinkmill/meetup-alternative#7]
There are two default exports in the same file, so build fails because of that.
[here](https://github.com/Thinkmill/meetup-alternative/blob/master/site/pages/profile.js#L10) and [here](https://github.com/Thinkmill/meetup-alternative/blob/master/site/pages/profile.js#L191)

**Comment by w01fgang** [comment]
@MadeByMike I can fix it

**Comment by MadeByMike** [comment]
Thanks!

**Comment by w01fgang** [comment]
@MadeByMike I fixed this and #8 issues in #10
