### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by w01fgang** [Thinkmill/meetup-alternative#8]
`yarn build` fails with an error `Error occurred prerendering /profile: TypeError: Cannot read property 'name' of undefined`
Temporary fixed by adding `if (!user) return 'No user'` before `user.name` statements. There is no profile link in the menu anyway.

**Comment by w01fgang** [comment]
@MadeByMike I can fix it
if there is no user I'll redirect to sign-in page

**Comment by MadeByMike** [comment]
Sounds good!
